### ISSUE TITLE
Error while starting a spark streaming job (when deploying the analytical server)

### ISSUE THREAD

**Issue by PavelPr** [NVIDIA-AI-IOT/deepstream_360_d_smart_parking_application#8]
Hi,

I am following the setup instructions and have hit an issue. I run the following command:

sudo docker exec -it spark-master /bin/bash
./bin/spark-submit --class com.nvidia.ds.stream.StreamProcessor --master spark://master:7077 --executor-memory 8G --total-executor-cores 4 /tmp/data/stream-360-1.0-jar-with-dependencies.jar

Then, in the course of its execution, I am getting errors of the following nature:

19/02/13 15:35:55 WARN clients.NetworkClient: Error while fetching metadata with correlation id XX: {metromind-start=LEADER_NOT_AVAILABLE}

Is anybody familiar with this?

Thanks!

**Comment by aiyerganapathy** [comment]
@PavelPr This indicates that your kafka docker wasn't started. Can you run the `stop` script and then the `start` script again. It should resolve your problem. Also, remember to pull the latest code as some changes related to kafka docker were made recently. Do let me know if your issue was resolved.

**Comment by aiyerganapathy** [comment]
I am closing the issue due to inactivity. You can reopen it, if you are still facing problems.
